### ISSUE TITLE
这个代码块的代码是哪几行呀？想用到别的主题里

### ISSUE THREAD

**Issue by yushengjiaohuang** [DreamSaddle/like-mac#1]
这个代码块真的太爱了，就是其他的一些元素不是很喜欢，就想自定义一下。无奈本人没学过css，不知道哪里是代码块的代码，方便告诉一下吗，谢谢啦。

**Comment by DreamSaddle** [comment]
[仿MAC窗口按钮](https://github.com/DreamSaddle/like-mac/blob/c03880170739dde8c3f75615f71b48cd945b42e9/like-mac.css#L446)
